export const currencies = {
  date: '11 Dec 2025 ',
  publishedCount: 240,
  rates: [
    {
      amount: 1,
      code: 'AUD',
      country: 'Australia',
      currency: 'dollar',
      rate: 13.764,
    },
    {
      amount: 1,
      code: 'BRL',
      country: 'Brazil',
      currency: 'real',
      rate: 3.8,
    },
    {
      amount: 1,
      code: 'BGN',
      country: 'Bulgaria',
      currency: 'lev',
      rate: 12.35,
    },
    {
      amount: 1,
      code: 'CAD',
      country: 'Canada',
      currency: 'dollar',
      rate: 14.983,
    },
    {
      amount: 1,
      code: 'CNY',
      country: 'China',
      currency: 'renminbi',
      rate: 2.929,
    },
    {
      amount: 1,
      code: 'DKK',
      country: 'Denmark',
      currency: 'krone',
      rate: 3.243,
    },
    {
      amount: 1,
      code: 'EUR',
      country: 'EMU',
      currency: 'euro',
      rate: 24.22,
    },
    {
      amount: 1,
      code: 'HKD',
      country: 'Hongkong',
      currency: 'dollar',
      rate: 2.657,
    },
    {
      amount: 100,
      code: 'HUF',
      country: 'Hungary',
      currency: 'forint',
      rate: 6.309,
    },
    {
      amount: 100,
      code: 'ISK',
      country: 'Iceland',
      currency: 'krona',
      rate: 16.299,
    },
    {
      amount: 1,
      code: 'XDR',
      country: 'IMF',
      currency: 'SDR',
      rate: 28.163,
    },
    {
      amount: 100,
      code: 'INR',
      country: 'India',
      currency: 'rupee',
      rate: 22.891,
    },
    {
      amount: 1000,
      code: 'IDR',
      country: 'Indonesia',
      currency: 'rupiah',
      rate: 1.24,
    },
    {
      amount: 1,
      code: 'ILS',
      country: 'Israel',
      currency: 'new shekel',
      rate: 6.437,
    },
    {
      amount: 100,
      code: 'JPY',
      country: 'Japan',
      currency: 'yen',
      rate: 13.291,
    },
    {
      amount: 1,
      code: 'MYR',
      country: 'Malaysia',
      currency: 'ringgit',
      rate: 5.03,
    },
    {
      amount: 1,
      code: 'MXN',
      country: 'Mexico',
      currency: 'peso',
      rate: 1.138,
    },
    {
      amount: 1,
      code: 'NZD',
      country: 'New Zealand',
      currency: 'dollar',
      rate: 12.019,
    },
    {
      amount: 1,
      code: 'NOK',
      country: 'Norway',
      currency: 'krone',
      rate: 2.048,
    },
    {
      amount: 100,
      code: 'PHP',
      country: 'Philippines',
      currency: 'peso',
      rate: 35.04,
    },
    {
      amount: 1,
      code: 'PLN',
      country: 'Poland',
      currency: 'zloty',
      rate: 5.731,
    },
    {
      amount: 1,
      code: 'RON',
      country: 'Romania',
      currency: 'leu',
      rate: 4.758,
    },
    {
      amount: 1,
      code: 'SGD',
      country: 'Singapore',
      currency: 'dollar',
      rate: 15.989,
    },
    {
      amount: 1,
      code: 'ZAR',
      country: 'South Africa',
      currency: 'rand',
      rate: 1.221,
    },
    {
      amount: 100,
      code: 'KRW',
      country: 'South Korea',
      currency: 'won',
      rate: 1.406,
    },
    {
      amount: 1,
      code: 'SEK',
      country: 'Sweden',
      currency: 'krona',
      rate: 2.233,
    },
    {
      amount: 1,
      code: 'CHF',
      country: 'Switzerland',
      currency: 'franc',
      rate: 25.955,
    },
    {
      amount: 100,
      code: 'THB',
      country: 'Thailand',
      currency: 'baht',
      rate: 65.106,
    },
    {
      amount: 100,
      code: 'TRY',
      country: 'Turkey',
      currency: 'lira',
      rate: 48.512,
    },
    {
      amount: 1,
      code: 'GBP',
      country: 'United Kingdom',
      currency: 'pound',
      rate: 27.679,
    },
    {
      amount: 1,
      code: 'USD',
      country: 'USA',
      currency: 'dollar',
      rate: 20.674,
    },
  ],
};
